version: '3'

services:

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    environment:
      - AXONSERVER_HOSTNAME=axonserver
    ports:
        - 8024:8024

  ddd-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AXONSERVER_HOST=axonserver
    ports:
      - 8081:8080